version: "3"

services:
  limesurvey:
    image: acspri/limesurvey:4.1.7
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
      LIMESURVEY_DEBUG: 2
    volumes:
      - C:\LSdocker2\html:/var/www/dev
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

  mail:
    image: djfarrelly/maildev
    ports:
      - "8081:80"
